# Generated by Django 5.0 on 2024-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game_role',
            field=models.IntegerField(choices=[(0, 'Citizen'), (1, 'Werewolf'), (2, 'Doctor'), (3, 'DEAD')], default=0),
        ),
    ]
