# Generated by Django 5.0 on 2023-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_status',
            field=models.IntegerField(choices=[(0, 'Starting'), (1, 'Active'), (2, 'Ended')]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.IntegerField(default=0),
        ),
    ]
