# Generated by Django 5.0 on 2024-01-12 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_alter_lobby_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='game_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby')),
            ],
        ),
    ]
