# Generated by Django 5.0 on 2024-01-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_alter_lobby_game_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_night', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby')),
            ],
        ),
    ]
