# Generated by Django 5.0 on 2024-01-17 14:28

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0010_alter_lobby_game_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playeid', models.AutoField(primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User)),
                ('username', models.CharField(max_length=20, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.RemoveField(
            model_name='round',
            name='lobby',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='name',
            new_name='lobbyname',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='game_admin',
        ),
        # migrations.RemoveField(
        #     model_name='lobby',
        #     name='id',
        # ),
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.AddField(
            model_name='lobby',
            name='game_cycle',
            field=models.IntegerField(choices=[(0, 'Day'), (1, 'Night')], default=0),
        ),
        # migrations.AddField(
        #     model_name='lobby',
        #     name='lobbyid',
        #     field=models.AutoField(default=0, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.IntegerField(max_length=20),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Citizen'), (1, 'Werewolf'), (2, 'Doctor')])),
                ('votecount', models.IntegerField(max_length=20)),
                ('lobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby')),
                ('playerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.player')),
            ],
        ),
        migrations.DeleteModel(
            name='GameCycle',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
