# Generated by Django 5.0 on 2024-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0011_player_remove_round_lobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='votecount',
            field=models.IntegerField(),
        ),
    ]
