# Generated by Django 5.0 on 2024-01-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0012_alter_lobby_max_players_alter_participant_votecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='lobbyname',
            new_name='lobby_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='lobbyid',
            new_name='lobbyId',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='playerid',
            new_name='playerId',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='votecount',
            new_name='vote_count',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='playeid',
            new_name='playerId',
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
