# Generated by Django 5.0 on 2024-01-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0014_lobby_game_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='playerId',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='participant',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lobbyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobby.lobby'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
