# Generated by Django 5.0 on 2024-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0015_remove_participant_playerid_participant_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
