# Generated by Django 5.0 on 2024-01-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0016_participant_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='id',
            new_name='lobbyid',
        ),
    ]
