# Generated by Django 5.0 on 2024-01-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0017_rename_id_lobby_lobbyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='lobbyid',
            new_name='id',
        ),
    ]
