# Generated by Django 5.0 on 2024-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0019_rename_id_lobby_lobbyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='killed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='rescued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.IntegerField(choices=[(0, 'Citizen'), (1, 'Werewolf'), (2, 'Doctor'), (3, 'DEAD')]),
        ),
    ]
