# Generated by Django 5.0 on 2024-02-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0020_participant_killed_participant_rescued_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='lobbyid',
            new_name='lobbyId',
        ),
    ]
