# Generated by Django 5.0 on 2024-03-14 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0021_rename_lobbyid_lobby_lobbyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='game_cycle',
            field=models.IntegerField(choices=[(0, 'Day'), (1, 'Night'), (2, 'End')], default=0),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
