# Generated by Django 5.0 on 2024-03-14 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0022_participant_dead_alter_lobby_game_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(16)]),
        ),
    ]
