# Generated by Django 5.0 on 2024-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0023_alter_lobby_max_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='voted',
            new_name='dayvoted',
        ),
        migrations.AddField(
            model_name='participant',
            name='nightvoted',
            field=models.BooleanField(default=False),
        ),
    ]
