# Generated by Django 5.0 on 2024-03-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0024_rename_voted_participant_dayvoted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
