# Generated by Django 5.0 on 2024-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0025_participant_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Active'), (2, 'Ended')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.IntegerField(choices=[(0, 'Citizen'), (1, 'Werewolf'), (2, 'Doctor'), (3, 'DEAD')], default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
