# Generated by Django 5.0 on 2024-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0026_alter_lobby_game_status_alter_participant_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.IntegerField(choices=[(0, 'Citizen'), (1, 'Werewolf'), (2, 'Doctor'), (3, 'DEAD'), (4, 'Spectate')], default=4),
        ),
    ]
