# Generated by Django 5.0 on 2024-04-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0027_alter_participant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lobbyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.participant')),
            ],
        ),
    ]
